[package]
name = "plotme"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
eframe = "0.28.1"
egui = { version = "0.28.1", features = ["serde"] }
egui_plot = "0.28.1"
plotters = "0.3.6"
rfd = "0.13"
serde = "1.0.209"
serde_json = "1.0.127"
